package com.example.lawsphere.data.utils

import android.content.Context
import android.print.PrintAttributes
import android.print.PrintManager
import android.webkit.WebView
import android.webkit.WebViewClient

object PdfGenerator {

    fun generatePdf(context: Context, documentTitle: String, htmlContent: String) {
        val webView = WebView(context)

        val styledHtml = """
            <html>
            <head>
                <style>
                    body { font-family: 'Times New Roman', serif; padding: 40px; line-height: 1.6; color: #000000; }
                    h1 { text-align: center; text-transform: uppercase; font-size: 24px; text-decoration: underline; }
                    h2 { text-align: center; font-size: 18px; margin-bottom: 30px; }
                    .content { font-size: 14px; text-align: justify; }
                    .signature { margin-top: 50px; text-align: right; font-weight: bold; }
                    .footer { margin-top: 30px; font-size: 10px; text-align: center; color: #555; }
                </style>
            </head>
            <body>
                $htmlContent
                <div class="footer">Generated by LawSphere AI - Legal Assistant</div>
            </body>
            </html>
        """.trimIndent()

        webView.webViewClient = object : WebViewClient() {
            override fun onPageFinished(view: WebView, url: String) {
                createWebPrintJob(context, view, documentTitle)
            }
        }

        webView.loadDataWithBaseURL(null, styledHtml, "text/HTML", "UTF-8", null)
    }

    private fun createWebPrintJob(context: Context, webView: WebView, jobName: String) {
        val printManager = context.getSystemService(Context.PRINT_SERVICE) as? PrintManager
        val printAdapter = webView.createPrintDocumentAdapter(jobName)

        val builder = PrintAttributes.Builder()
        builder.setMediaSize(PrintAttributes.MediaSize.ISO_A4)

        printManager?.print(
            jobName,
            printAdapter,
            builder.build()
        )
    }
}